---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Copy nginx.conf
  template:
    src: ./templates/nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
      
- name: Start service Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Enable service Nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
